# This template reboots a CI agent.

parameters:
  pool: ''
  agentName: ''

jobs:
- job: reboot_${{ parameters.pool }}_${{ replace(parameters.agentName, '-', '_') }}
  displayName: reboot-${{ parameters.pool }}-${{ parameters.agentName }}
  pool:
    name: ${{ parameters.pool }}
    demands: Agent.Name -equals ${{ parameters.agentName }}
  workspace:
    clean: all
  variables:
  - name: runCodesignValidationInjection
    value: false
  timeoutInMinutes: 5

  steps:

  - task: PowerShell@2
    displayName: Reboot
    timeoutInMinutes: 5
    inputs:
      targetType: inline
      script: "shutdown.exe /r /f /t 0"
